# Generated by Django 3.1.5 on 2021-01-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
