# Generated by Django 3.1.5 on 2021-01-18 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_notes_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
        migrations.AddField(
            model_name='notes',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['doc'])]),
        ),
        migrations.AddField(
            model_name='notes',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
        migrations.AlterField(
            model_name='notes',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
