# Generated by Django 3.1.5 on 2021-01-19 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210118_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='publish',
            field=models.IntegerField(blank=True, default=0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
    ]
